#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Namespace
metadata:
  name: vperm
---
apiVersion: v1
kind: Secret
data:
  password: #@ base64.encode(data.values.password)
  server: #@ base64.encode(data.values.server)
  user: #@ base64.encode(data.values.user)
metadata:
  name: vsphere-creds
  namespace: vperm
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vperm
  namespace: vperm
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - env:
        - name: VSPHERE_HOST
          valueFrom:
            secretKeyRef:
              name: vsphere-creds
              key: server
        - name: VSPHERE_USERNAME
          valueFrom:
            secretKeyRef:
              name: vsphere-creds
              key: user
        - name: VSPHERE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vsphere-creds
              key: password
        image: #@ data.values.image
        imagePullPolicy: IfNotPresent
        name: vperm
